### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by joobert** [DenysMb/ChatAI-Plasmoid#1]
This plasmoid is great! Very much needed, and simple UI is always best. I think these QOL feature requests would really polish your work:

- The option to hide the "Keep Open" pin from the header
- The option to hide the header entirely if only one LLM is enabled.
- Similar to dynamically using the favicon as the plasmoid's icon, the option to instead use the LLM's corresponding vector icon (both light and dark) as the plasmoid's icon. I'd be happy to fetch and size the SVGs for you if you do decide to implement this.

**Comment by DenysMb** [comment]
Hey!

I just added the option to hide the entire header when only one model is enabled.
I will add the option to individually hide both buttons from the header (since now we have the same options in the context menu).
I have the models' icon, it is a good idea to use then instead of the favicon, since the favicon do not render very well. I will try to do this too.

**Comment by DenysMb** [comment]
The option to hide the header buttons was added now in this new release: https://github.com/DenysMb/ChatAI-Plasmoid/releases/tag/1.2.0

**Comment by joobert** [comment]
Super clean! Thank you, looking forward to being able to send messages with the Enter key.

**Comment by DenysMb** [comment]
All of this is implemented now.
