### ISSUE TITLE
Font Color

### ISSUE THREAD

**Issue by samirgaire10** [DenysMb/ChatAI-Plasmoid#12]
"After restarting or logging out of my PC and then opening this widget, I noticed that both the font from the 'AI selection' heading and the background are black. This makes it difficult to view and read the content effectively."

making it hard to read

![Screenshot_20240619_111717](https://github.com/DenysMb/ChatAI-Plasmoid/assets/118608337/f16549bb-2206-4dcd-869c-343a77b2e971)

**Comment by DenysMb** [comment]
I saw this behavior in another widget, I thought that this was something "out of my control". But I'll check if I can just change the text color of the options in the combobox. If it's possible, I can use theme colors to fix this.
I'll have a look.

**Comment by DenysMb** [comment]
Fixed in https://github.com/DenysMb/ChatAI-Plasmoid/commit/d7c38683cb5bfcf1f7dc03e8908a5373d931f38c
The ComboBox from Plasma Components doesn't accept an array of objects as model. I was using QT ComboBox because of this, but this was causing this issue.
Now I am using the ComboBox from PlasmaComponents but for that I needed to add a little logic in the code (since now I am using an array of strings instead of an array of object).
